/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiWebhooksAsaasRouteImport } from './routes/api/webhooks/asaas'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/app/subscription'
import { Route as AuthenticatedAppStudyRouteImport } from './routes/_authenticated/app/study'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app/history'
import { Route as AuthenticatedAdminVersionsRouteImport } from './routes/_authenticated/admin/versions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTopicsRouteImport } from './routes/_authenticated/admin/topics'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin/subscriptions'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin/subjects'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminPositionsRouteImport } from './routes/_authenticated/admin/positions'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin/packages'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminExportRouteImport } from './routes/_authenticated/admin/export'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin/exams'
import { Route as AuthenticatedAdminDistributionsRouteImport } from './routes/_authenticated/admin/distributions'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminBoardsRouteImport } from './routes/_authenticated/admin/boards'
import { Route as AuthenticatedAppStudyIndexRouteImport } from './routes/_authenticated/app/study.index'
import { Route as AuthenticatedAdminSubjectsIndexRouteImport } from './routes/_authenticated/admin/subjects.index'
import { Route as AuthenticatedAppStudySessionIdRouteImport } from './routes/_authenticated/app/study.$sessionId'
import { Route as AuthenticatedAdminSubjectsSubjectIdRouteImport } from './routes/_authenticated/admin/subjects.$subjectId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiWebhooksAsaasRoute = ApiWebhooksAsaasRouteImport.update({
  id: '/api/webhooks/asaas',
  path: '/api/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppStudyRoute = AuthenticatedAppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminVersionsRoute =
  AuthenticatedAdminVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTopicsRoute =
  AuthenticatedAdminTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPositionsRoute =
  AuthenticatedAdminPositionsRouteImport.update({
    id: '/positions',
    path: '/positions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExportRoute =
  AuthenticatedAdminExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDistributionsRoute =
  AuthenticatedAdminDistributionsRouteImport.update({
    id: '/distributions',
    path: '/distributions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBoardsRoute =
  AuthenticatedAdminBoardsRouteImport.update({
    id: '/boards',
    path: '/boards',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppStudyIndexRoute =
  AuthenticatedAppStudyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppStudyRoute,
  } as any)
const AuthenticatedAdminSubjectsIndexRoute =
  AuthenticatedAdminSubjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSubjectsRoute,
  } as any)
const AuthenticatedAppStudySessionIdRoute =
  AuthenticatedAppStudySessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedAppStudyRoute,
  } as any)
const AuthenticatedAdminSubjectsSubjectIdRoute =
  AuthenticatedAdminSubjectsSubjectIdRouteImport.update({
    id: '/$subjectId',
    path: '/$subjectId',
    getParentRoute: () => AuthenticatedAdminSubjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/admin/boards': typeof AuthenticatedAdminBoardsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/distributions': typeof AuthenticatedAdminDistributionsRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRouteWithChildren
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/study': typeof AuthenticatedAppStudyRouteWithChildren
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/subjects/$subjectId': typeof AuthenticatedAdminSubjectsSubjectIdRoute
  '/app/study/$sessionId': typeof AuthenticatedAppStudySessionIdRoute
  '/admin/subjects/': typeof AuthenticatedAdminSubjectsIndexRoute
  '/app/study/': typeof AuthenticatedAppStudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/boards': typeof AuthenticatedAdminBoardsRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/distributions': typeof AuthenticatedAdminDistributionsRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/subjects/$subjectId': typeof AuthenticatedAdminSubjectsSubjectIdRoute
  '/app/study/$sessionId': typeof AuthenticatedAppStudySessionIdRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsIndexRoute
  '/app/study': typeof AuthenticatedAppStudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/admin/boards': typeof AuthenticatedAdminBoardsRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/distributions': typeof AuthenticatedAdminDistributionsRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/_authenticated/admin/export': typeof AuthenticatedAdminExportRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRouteWithChildren
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/study': typeof AuthenticatedAppStudyRouteWithChildren
  '/_authenticated/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/api/webhooks/asaas': typeof ApiWebhooksAsaasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/subjects/$subjectId': typeof AuthenticatedAdminSubjectsSubjectIdRoute
  '/_authenticated/app/study/$sessionId': typeof AuthenticatedAppStudySessionIdRoute
  '/_authenticated/admin/subjects/': typeof AuthenticatedAdminSubjectsIndexRoute
  '/_authenticated/app/study/': typeof AuthenticatedAppStudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/admin/boards'
    | '/admin/courses'
    | '/admin/distributions'
    | '/admin/exams'
    | '/admin/export'
    | '/admin/import'
    | '/admin/packages'
    | '/admin/positions'
    | '/admin/questions'
    | '/admin/subjects'
    | '/admin/subscriptions'
    | '/admin/topics'
    | '/admin/users'
    | '/admin/versions'
    | '/app/history'
    | '/app/study'
    | '/app/subscription'
    | '/api/webhooks/asaas'
    | '/admin/'
    | '/app/'
    | '/admin/subjects/$subjectId'
    | '/app/study/$sessionId'
    | '/admin/subjects/'
    | '/app/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/boards'
    | '/admin/courses'
    | '/admin/distributions'
    | '/admin/exams'
    | '/admin/export'
    | '/admin/import'
    | '/admin/packages'
    | '/admin/positions'
    | '/admin/questions'
    | '/admin/subscriptions'
    | '/admin/topics'
    | '/admin/users'
    | '/admin/versions'
    | '/app/history'
    | '/app/subscription'
    | '/api/webhooks/asaas'
    | '/admin'
    | '/app'
    | '/admin/subjects/$subjectId'
    | '/app/study/$sessionId'
    | '/admin/subjects'
    | '/app/study'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/boards'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/distributions'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/export'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/positions'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/topics'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/versions'
    | '/_authenticated/app/history'
    | '/_authenticated/app/study'
    | '/_authenticated/app/subscription'
    | '/api/webhooks/asaas'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/subjects/$subjectId'
    | '/_authenticated/app/study/$sessionId'
    | '/_authenticated/admin/subjects/'
    | '/_authenticated/app/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiWebhooksAsaasRoute: typeof ApiWebhooksAsaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/webhooks/asaas': {
      id: '/api/webhooks/asaas'
      path: '/api/webhooks/asaas'
      fullPath: '/api/webhooks/asaas'
      preLoaderRoute: typeof ApiWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/subscription': {
      id: '/_authenticated/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/study': {
      id: '/_authenticated/app/study'
      path: '/study'
      fullPath: '/app/study'
      preLoaderRoute: typeof AuthenticatedAppStudyRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/versions': {
      id: '/_authenticated/admin/versions'
      path: '/versions'
      fullPath: '/admin/versions'
      preLoaderRoute: typeof AuthenticatedAdminVersionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/topics': {
      id: '/_authenticated/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AuthenticatedAdminTopicsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/positions': {
      id: '/_authenticated/admin/positions'
      path: '/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AuthenticatedAdminPositionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/export': {
      id: '/_authenticated/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AuthenticatedAdminExportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/distributions': {
      id: '/_authenticated/admin/distributions'
      path: '/distributions'
      fullPath: '/admin/distributions'
      preLoaderRoute: typeof AuthenticatedAdminDistributionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/boards': {
      id: '/_authenticated/admin/boards'
      path: '/boards'
      fullPath: '/admin/boards'
      preLoaderRoute: typeof AuthenticatedAdminBoardsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/study/': {
      id: '/_authenticated/app/study/'
      path: '/'
      fullPath: '/app/study/'
      preLoaderRoute: typeof AuthenticatedAppStudyIndexRouteImport
      parentRoute: typeof AuthenticatedAppStudyRoute
    }
    '/_authenticated/admin/subjects/': {
      id: '/_authenticated/admin/subjects/'
      path: '/'
      fullPath: '/admin/subjects/'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSubjectsRoute
    }
    '/_authenticated/app/study/$sessionId': {
      id: '/_authenticated/app/study/$sessionId'
      path: '/$sessionId'
      fullPath: '/app/study/$sessionId'
      preLoaderRoute: typeof AuthenticatedAppStudySessionIdRouteImport
      parentRoute: typeof AuthenticatedAppStudyRoute
    }
    '/_authenticated/admin/subjects/$subjectId': {
      id: '/_authenticated/admin/subjects/$subjectId'
      path: '/$subjectId'
      fullPath: '/admin/subjects/$subjectId'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsSubjectIdRouteImport
      parentRoute: typeof AuthenticatedAdminSubjectsRoute
    }
  }
}

interface AuthenticatedAdminSubjectsRouteChildren {
  AuthenticatedAdminSubjectsSubjectIdRoute: typeof AuthenticatedAdminSubjectsSubjectIdRoute
  AuthenticatedAdminSubjectsIndexRoute: typeof AuthenticatedAdminSubjectsIndexRoute
}

const AuthenticatedAdminSubjectsRouteChildren: AuthenticatedAdminSubjectsRouteChildren =
  {
    AuthenticatedAdminSubjectsSubjectIdRoute:
      AuthenticatedAdminSubjectsSubjectIdRoute,
    AuthenticatedAdminSubjectsIndexRoute: AuthenticatedAdminSubjectsIndexRoute,
  }

const AuthenticatedAdminSubjectsRouteWithChildren =
  AuthenticatedAdminSubjectsRoute._addFileChildren(
    AuthenticatedAdminSubjectsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBoardsRoute: typeof AuthenticatedAdminBoardsRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminDistributionsRoute: typeof AuthenticatedAdminDistributionsRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRoute
  AuthenticatedAdminExportRoute: typeof AuthenticatedAdminExportRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminPositionsRoute: typeof AuthenticatedAdminPositionsRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRouteWithChildren
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminTopicsRoute: typeof AuthenticatedAdminTopicsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVersionsRoute: typeof AuthenticatedAdminVersionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBoardsRoute: AuthenticatedAdminBoardsRoute,
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
    AuthenticatedAdminDistributionsRoute: AuthenticatedAdminDistributionsRoute,
    AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRoute,
    AuthenticatedAdminExportRoute: AuthenticatedAdminExportRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
    AuthenticatedAdminPositionsRoute: AuthenticatedAdminPositionsRoute,
    AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
    AuthenticatedAdminSubjectsRoute:
      AuthenticatedAdminSubjectsRouteWithChildren,
    AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
    AuthenticatedAdminTopicsRoute: AuthenticatedAdminTopicsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVersionsRoute: AuthenticatedAdminVersionsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppStudyRouteChildren {
  AuthenticatedAppStudySessionIdRoute: typeof AuthenticatedAppStudySessionIdRoute
  AuthenticatedAppStudyIndexRoute: typeof AuthenticatedAppStudyIndexRoute
}

const AuthenticatedAppStudyRouteChildren: AuthenticatedAppStudyRouteChildren = {
  AuthenticatedAppStudySessionIdRoute: AuthenticatedAppStudySessionIdRoute,
  AuthenticatedAppStudyIndexRoute: AuthenticatedAppStudyIndexRoute,
}

const AuthenticatedAppStudyRouteWithChildren =
  AuthenticatedAppStudyRoute._addFileChildren(
    AuthenticatedAppStudyRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppStudyRoute: typeof AuthenticatedAppStudyRouteWithChildren
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppStudyRoute: AuthenticatedAppStudyRouteWithChildren,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiWebhooksAsaasRoute: ApiWebhooksAsaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
